import ZeroMath.Numbers.OrdinalNatural.Decimal.Progressions.InfiniteArithmetic
import ZeroMath.Numbers.OrdinalNatural.Decimal.Progressions.FiniteArithmeticIncreasing
import ZeroMath.Numbers.OrdinalNatural.Decimal.Progressions.ArithmeticDecreasing
