import ZeroMath.Numbers.OrdinalNatural.Peano.Progressions.InfiniteArithmetic
import ZeroMath.Numbers.OrdinalNatural.Peano.Progressions.FiniteArithmeticIncreasing
import ZeroMath.Numbers.OrdinalNatural.Peano.Progressions.ArithmeticDecreasing
