import ZeroMath.Numbers.CardinalNatural.Decimal.Progressions.InfiniteArithmetic
import ZeroMath.Numbers.CardinalNatural.Decimal.Progressions.FiniteArithmeticIncreasing
import ZeroMath.Numbers.CardinalNatural.Decimal.Progressions.ArithmeticDecreasing
